dbt_ecommerce:
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_ANALYTICAL_DB', 'analytical') }}"
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: "{{ env_var('CLICKHOUSE_HTTP_PORT', '8124') | as_number }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'clickhouse_admin') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'clickhouse_admin_pass') }}"
      secure: False
  target: dev
