{{ config(
    materialized='table',
    engine='MergeTree()',
    partition_by='toYYYYMM(order_purchase_timestamp)',
    order_by='(customer_state, product_category_name_english, order_purchase_timestamp, order_id, order_item_id)',
    settings={'index_granularity': 8192}
) }}

WITH payments_aggregated AS (
    SELECT
        order_id,
        groupArray(payment_type) AS payment_types,
        groupArray(toUInt8(payment_installments)) AS payment_installments,
        sum(payment_value) AS total_order_payment_value
    FROM {{ ref('stg_order_payments') }}
    GROUP BY order_id
),

reviews_latest AS (
    SELECT
        order_id,
        review_score,
        review_answer_timestamp
    FROM (
        SELECT
            order_id,
            review_score,
            review_answer_timestamp,
            row_number() OVER (PARTITION BY order_id ORDER BY review_answer_timestamp DESC) AS rn
        FROM {{ ref('stg_order_reviews') }}
    )
    WHERE rn = 1
)

SELECT
    -------------------------------------------------------------------------
    -- 1. ORDER BASE IDENTIFIERS & STATES
    -------------------------------------------------------------------------
    o.order_id AS order_id,
    o.customer_id AS customer_id,
    c.customer_unique_id AS customer_unique_id,
    cast(o.order_status, 'LowCardinality(String)') AS order_status,
    
    -------------------------------------------------------------------------
    -- 2. TIMESTAMPS & SLA RECORDINGS
    -------------------------------------------------------------------------
    o.order_purchase_timestamp AS order_purchase_timestamp,
    o.order_approved_at AS order_approved_at,
    o.order_delivered_carrier_date AS order_delivered_carrier_date,
    o.order_delivered_customer_date AS order_delivered_customer_date,
    o.order_estimated_delivery_date AS order_estimated_delivery_date,
    
    -------------------------------------------------------------------------
    -- 3. ITEM-LEVEL METRICS & GRAIN LOGIC
    -------------------------------------------------------------------------
    toUInt8(oi.order_item_id) AS order_item_id,
    oi.product_id AS product_id,
    oi.seller_id AS seller_id,
    oi.shipping_limit_date AS shipping_limit_date,
    oi.price AS price,
    oi.freight_value AS freight_value,
    
    -------------------------------------------------------------------------
    -- 4. DENORMALIZED PRODUCT DIMENSIONS
    -------------------------------------------------------------------------
    cast(coalesce(t.product_category_name_english, 'unknown'), 'LowCardinality(String)') AS product_category_name_english,
    cast(p.product_weight_g, 'Nullable(UInt32)') AS product_weight_g,
    cast(p.product_length_cm * p.product_height_cm * p.product_width_cm, 'Nullable(UInt32)') AS product_volume_cm3,
    
    -------------------------------------------------------------------------
    -- 5. DENORMALIZED GEOGRAPHY DIMENSIONS (CUSTOMERS & SELLERS)
    -------------------------------------------------------------------------
    c.customer_zip_code_prefix AS customer_zip_code_prefix,
    cast(c.customer_city, 'LowCardinality(String)') AS customer_city,
    cast(c.customer_state, 'LowCardinality(String)') AS customer_state,
    s.seller_zip_code_prefix AS seller_zip_code_prefix,
    cast(s.seller_city, 'LowCardinality(String)') AS seller_city,
    cast(s.seller_state, 'LowCardinality(String)') AS seller_state,
    
    -------------------------------------------------------------------------
    -- 6. ORDER-LEVEL PAYMENTS (PREVENTING CARTESIAN DUPES VIA ARRAYS)
    -------------------------------------------------------------------------
    cast(coalesce(pay.payment_types, cast([], 'Array(String)')), 'Array(LowCardinality(String))') AS payment_types,
    coalesce(pay.payment_installments, cast([], 'Array(UInt8)')) AS payment_installments,
    coalesce(pay.total_order_payment_value, 0.0) AS total_order_payment_value,
    
    -------------------------------------------------------------------------
    -- 7. REVIEWS & QUALITY METRICS
    -------------------------------------------------------------------------
    cast(rev.review_score, 'Nullable(UInt8)') AS review_score,
    rev.review_answer_timestamp AS review_answer_timestamp,
    
    -------------------------------------------------------------------------
    -- 8. OPERATIONAL METRICS GENERATED BY DBT
    -------------------------------------------------------------------------
    cast(if(o.order_delivered_customer_date IS NOT NULL, dateDiff('second', o.order_purchase_timestamp, o.order_delivered_customer_date) / 86400.0, NULL), 'Nullable(Float32)') AS delivery_actual_duration_days,
    cast(dateDiff('second', o.order_purchase_timestamp, o.order_estimated_delivery_date) / 86400.0, 'Nullable(Float32)') AS delivery_estimated_duration_days,
    toUInt8(if(o.order_delivered_customer_date > o.order_estimated_delivery_date, 1, 0)) AS is_delivery_delayed,
    cast(if(oi.price + oi.freight_value > 0, oi.freight_value / (oi.price + oi.freight_value), 0.0), 'Float32') AS freight_ratio

FROM {{ ref('stg_order_items') }} oi
INNER JOIN {{ ref('stg_orders') }} o ON oi.order_id = o.order_id
LEFT JOIN {{ ref('stg_customers') }} c ON o.customer_id = c.customer_id
LEFT JOIN {{ ref('stg_sellers') }} s ON oi.seller_id = s.seller_id
LEFT JOIN {{ ref('stg_products') }} p ON oi.product_id = p.product_id
LEFT JOIN {{ ref('stg_product_category_name_translation') }} t ON p.product_category_name = t.product_category_name
LEFT JOIN payments_aggregated pay ON o.order_id = pay.order_id
LEFT JOIN reviews_latest rev ON o.order_id = rev.order_id
